name: CI/CD Pipeline with Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, intl
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHP CodeSniffer and Fix
        run: |
          ./vendor/bin/phpcbf --standard=your_custom_standard.xml src/ || true  # Retter fejl automatisk
        continue-on-error: true  # Fortsæt selv hvis der er uløste fejl

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit --testdox

  deploy:
    runs-on: ubuntu-latest
    needs: php-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          remote-dir: "/staging/wp-content/plugins"
          git-ftp-args: --auto-init
